site_name: Headbreaker - Jigsaw Puzzles Framework for JavaScript
site_url: https://flbulgarelli.github.io/headbreaker
nav:
  - Home: index.md
repo_url: "https://github.com/flbulgarelli/headbreaker"
copyright: '© Copyright 2020 Franco Leonardo Bulgarelli'
docs_dir: docs
